df_core:
  «Money»_Currency:
    enum: '::Df::Core::Enum::Currency::Paypal'
    default: 'USD'
    client: true
  «Money»_Currency_Symbol:
    default: '$'
    client: true
  «Money»_Currency_Symbol_Position:
    enum: '::Df::Core::Enum::Position::BeforeAfter'
    default: 'before'
    client: true
  «Money»_Delimit_Currency_Symbol_from_Amount:
    default: false
    client: true
  «Money»_Number_of_Decimals:
    default: 0
    client: true
  «Money»_Decimal_Separator:
    default: '.'
    client: true
  «Money»_Thousands_Separator:
    enum: '::Df::Core::Enum::Format::ThousandsSeparator'
    default: 'thin_space'
    client: true